# Generated by Django 4.0.4 on 2022-05-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorBackup',
            fields=[
                ('author_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author_backup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=20)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('author_info', models.TextField(blank=True, null=True)),
                ('author_photo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('board_content', models.TextField(blank=True, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('translator', models.TextField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookBackup2',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('translator', models.TextField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookBackup3',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('translator', models.TextField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCoverBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('cover_large', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_cover_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCoverBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('cover_large', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_cover_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDescBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_desc_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDescBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_desc_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDescPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_desc_practice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookGradeBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('review_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_grade_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookGradeBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('review_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_grade_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookSizeBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_size_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookSizeBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_size_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('comment_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoverTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cover_large', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cover_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DislikeTab',
            fields=[
                ('dislike_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dislike_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isbn13', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'db_table': 'isbn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsbnBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('isbn13', models.CharField(blank=True, max_length=14, null=True)),
                ('book_id', models.CharField(blank=True, db_column='BOOK_ID', max_length=20, null=True)),
            ],
            options={
                'db_table': 'isbn_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsbnBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('isbn13', models.CharField(blank=True, max_length=14, null=True)),
                ('book_id', models.CharField(blank=True, db_column='BOOK_ID', max_length=20, null=True)),
            ],
            options={
                'db_table': 'isbn_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeTab',
            fields=[
                ('like_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like_tab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('phrase_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phrase_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phrase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhraseBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.CharField(max_length=20)),
                ('phrase_content', models.TextField(blank=True, null=True)),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'phrase_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhraseBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.CharField(max_length=20)),
                ('phrase_content', models.TextField(blank=True, null=True)),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'phrase_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('review_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewBackup2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=20)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'review_backup2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewBackup3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=20)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('book_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'review_backup3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestDf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('cover_large', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_df',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, db_column='COVER', null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
                ('author_id', models.CharField(blank=True, db_column='AUTHOR_ID', max_length=20, null=True)),
                ('pubdate', models.DateField(blank=True, db_column='PUBDATE', null=True)),
                ('translator', models.TextField(blank=True, db_column='TRANSLATOR', null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('author', models.TextField(blank=True, db_column='AUTHOR', null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('book_id', models.CharField(blank=True, db_column='BOOK_ID', max_length=20, null=True)),
            ],
            options={
                'db_table': 'yes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDesc',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rcm.book')),
                ('content', models.TextField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_desc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookGrade',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rcm.book')),
                ('score', models.FloatField(blank=True, null=True)),
                ('review_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookHistory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rcm.user')),
                ('score', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rcm.bookdesc')),
                ('cover_large', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_cover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookSize',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rcm.bookdesc')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_size',
                'managed': False,
            },
        ),
    ]
